"""Initial migration - create all tables

Revision ID: abcd14f8fbc6
Revises: 
Create Date: 2025-09-22 12:13:50.418183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abcd14f8fbc6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activation_codes',
    sa.Column('id', sa.UUID(), nullable=False, comment='激活码唯一标识'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='激活码字符串'),
    sa.Column('total_uses', sa.Integer(), nullable=True, comment='总使用次数'),
    sa.Column('used_count', sa.Integer(), nullable=True, comment='已使用次数'),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', 'EXPIRED', name='activationcodestatus'), nullable=True, comment='激活码状态'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='过期时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activation_codes_code'), 'activation_codes', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='用户唯一标识'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='用户邮箱'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希值'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', name='userstatus'), nullable=True, comment='用户状态'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False, comment='简历唯一标识'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户ID'),
    sa.Column('personal_info', sa.JSON(), nullable=False, comment='个人基本信息JSON'),
    sa.Column('education', sa.JSON(), nullable=False, comment='教育经历JSON'),
    sa.Column('experience', sa.JSON(), nullable=False, comment='工作经验JSON'),
    sa.Column('skills', sa.JSON(), nullable=False, comment='技能信息JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='日志唯一标识'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户ID'),
    sa.Column('website_url', sa.String(length=500), nullable=False, comment='使用的网站URL'),
    sa.Column('fields_count', sa.Integer(), nullable=False, comment='检测到的字段数量'),
    sa.Column('success_count', sa.Integer(), nullable=False, comment='成功填写的字段数量'),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='使用时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_activations',
    sa.Column('id', sa.UUID(), nullable=False, comment='记录唯一标识'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='关联用户ID'),
    sa.Column('activation_code_id', sa.UUID(), nullable=False, comment='关联激活码ID'),
    sa.Column('remaining_uses', sa.Integer(), nullable=True, comment='剩余使用次数'),
    sa.Column('activated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='激活时间'),
    sa.ForeignKeyConstraint(['activation_code_id'], ['activation_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_activations')
    op.drop_table('usage_logs')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_activation_codes_code'), table_name='activation_codes')
    op.drop_table('activation_codes')
    # ### end Alembic commands ###
